import { position } from "@chakra-ui/react";

//สำหรับหน้า Assessment and Component AssessHaringLossForm And AssessHaringLossTab
export const TextsAssessmentHearingLossPage = {
  th: {
    headerHl: "ประเมินความเสี่ยงการรับสัมผัสเสียงดัง",
    backBtn: "กลับสู่หน้าหลัก",
    clearData: "ล้างข้อมูล",
    assessmentAgain: "ประเมินอีกครั้ง",
    saveData: "บันทึกข้อมูล",
    infoData: "ข้อมูลผู้ได้รับการประเมิน",
    fname: "ชื่อ",
    lname: "นามสกุล",
    pinLocation: "ปักหมุดสถานที่ประเมิน",
    error: {
      title1: "ไม่พบชื่อนามสกุลในระบบ",
      title2: "กรุณาตรวจสอบชื่อนามสกุลอีกครั้ง",
      title3: "หรือลงทะเบียนผู้ประกอบอาชีพทำครกหิน",
      position: "กรุณาเลือกตำแหน่งงาน",
      soundLevel1: "กรุณาใส่ข้อมูลระดับความดันเสียง",
      soundLevel2: "ข้อมูลระดับความดันเสียงต้องไม่ต่ำกว่า 0 db(A)",
      workingHours1: "ข้อมูลชั่วโมงการทำงานต่อวันต้องไม่ต่ำกว่า 1 ชั่วโมง",
      workingHours2: "กรุณาใส่ข้อมูลชั่วโมงการทำงานต่อวัน",
      workingHours3: "ข้อมูลชั่วโมงการทำงานต่อวันต้องไม่เกินกว่า 24 ชั่วโมง",
      bodyHeight1: "ข้อมูลส่วนสูงร่างกายต้องไม่ต่ำกว่า 1 เซนติเมตร",
      bodyHeight2: "กรุณาใส่ข้อมูลส่วนสูงร่างกาย",
    },
    register: "ลงทะเบียน",
    cancelBtn: "ยกเลิก",
    //AssessHaringLossTab
    position: "ตำแหน่งงาน",
    positionOptions: {
      "": "เลือกตำแหน่งงาน",
      "เจาะหิน": "เจาะหิน",
      "ตัดหิน/ผ่าหิน": "ตัดหิน/ผ่าหิน",
      "เจียร์/แกะสลักหิน": "เจียร์/แกะสลักหิน",
      "อื่น ๆ": "อื่น ๆ",
    },
    soundLevel: {
      title: "ระดับเสียง",
      low: "ต่ำสุด",
      avg: "เฉลี่ย",
      high: "สูงสุด",
    },
    placeholder: {
      soundLevel: "ใส่เฉพาะตัวเลข",
    },
    dbA: "db(A)",
    workingHours: { title: "ชั่วโมงการทำงานต่อวัน", hour: "ชั่วโมง" },
    bodyHeight: { title: "ส่วนสูงร่างกาย", cm: "เซนติเมตร" },
    earSymptoms: {
      title: "อาการผิดปกติเกี่ยวกับหู",
      no: "ไม่มีอาการ",
      yes: "มีอาการ",
    },
    assessmentBtn: "ประเมินความเสี่ยง",
  },
  en: {
    headerHl: "Hearing Loss Assessment",
    backBtn: "Back to Main",
    clearData: "Clear Data",
    assessmentAgain: "Assessment Again",
    saveData: "Save Data",
    infoData: "Assessment Data",
    fname: "Firstname",
    lname: "Lastname",
    pinLocation: "Pin Location",
    error: {
      title1: "Name not found in the Database",
      title2: "Please check your Firstname & Lastname",
      title3: "Or Register",
      position: "Please select a position",
      soundLevel1: "Please enter sound level",
      soundLevel2: "Sound level must be greater than or equal to 0",
      workingHours1: "Working hours per day must be greater than or equal to 1",
      workingHours2: "Please enter working hours per day",
      workingHours3: "Working hours per day must be less than or equal to 24",
      bodyHeight1: "Height must be greater than or equal to 1",
      bodyHeight2: "Please enter height",
    },
    register: "Register",
    cancelBtn: "Cancel",
    //AssessHaringLossTab
    position: "position",
    positionOptions: {
      "": "Select a position",
      "เจาะหิน": "drilling",
      "ตัดหิน/ผ่าหิน": "cutting",
      "เจียร์/แกะสลักหิน": "cracking",
      "อื่น ๆ": "other",  
    },
    soundLevel: {
      title: "Sound Level",
      low: "Lowest",
      avg: "Avg.",
      high: "Highest",
    },
    placeholder: {
      soundLevel: "Only numbers",
    },
    dbA: "db(A)",
    workingHours: { title: "Woriking Hours per Day", hour: "Hour(s)" },
    bodyHeight: { title: "Hieght", cm: "cm" },
    earSymptoms: {
      title: "Ear Symptoms",
      no: "No, I don't have any symptoms",
      yes: "Yes, I have some symptoms",
    },
    assessmentBtn: "Assessment",
  },
};
