import { medicalOptions } from "@/components/register/worker/Option";

export const TextHealthInfoTab = {
  th: {
    weight: "น้ำหนักร่างกาย",
    weightUnit: "กิโลกรัม",
    healthInsurance: "สิทธิการรักษาพยาบาล",
    medicalOptions: {
      "": "เลือกสิทธิการรักษาพยาบาล",
      "ไม่มีสิทธิการรักษาพยาบาล": "ไม่มีสิทธิการรักษาพยาบาล",
      "สิทธิข้าราชการ": "สิทธิข้าราชการ",
      "สิทธิประกันสังคม": "สิทธิประกันสังคม",
      "สิทธิบัตรทอง 30 บาท": "สิทธิบัตรทอง 30 บาท",
      "สิทธิบัตรประกันสุขภาพต่างด้าว": "สิทธิบัตรประกันสุขภาพต่างด้าว",
      "สิทธิ อ.ส.ม.": "สิทธิ อ.ส.ม.",
      "อื่น ๆ": "อื่น ๆ",
    },
    diseases: "โรคประจำตัว",
    diseasesOptions: {
      no: "ไม่มี",
      silicosis: "โรคปอดฝุ่นหิน (ซิลิโคสิส)",
      hearingLoss: "โรคประสาทหูเสื่อม/สูญเสียการได้ยิน",
      diabetes: "โรคเบาหวาน",
      heartDisease: "โรคหลอดเลือดสมองและหัวใจ",
      emphysema: "โรคถุงลมโป่งพอง",
      cancer: "โรคมะเร็ง",
      hypertension: "โรคความดันโลหิตสูง",
      liverDisease: "โรคไขมันในเลือดสูง",
      other: "อื่น ๆ",
    },
    abnormalEarSymptoms: "ระบุอาการผิดปกติเกี่ยวกับหู",
  },
  en: {
    weight: "Body Weight",
    weightUnit: "kg",
    healthInsurance: "Medical treatment rights",
    medicalOptions: {
      "": "Select Medical treatment rights",
      "ไม่มีสิทธิการรักษาพยาบาล": "No Medical Treatment Rights",
      "สิทธิข้าราชการ": "Civil servant rights",
      "สิทธิประกันสังคม": "Social security rights",
      "สิทธิบัตรทอง 30 บาท": "30 baht gold card",
      "สิทธิบัตรประกันสุขภาพต่างด้าว": "Foreign health insurance card",
      "สิทธิ อ.ส.ม.": "Rights of the A.S.M.",
      "อื่น ๆ": "Other",
    },
    diseases: "Diseases",
    diseasesOptions: {
      no: "No",
      silicosis: "Silicosis",
      hearingLoss: "Hearing Loss",
      diabetes: "Diabetes",
      heartDisease: "Heart Disease",
      emphysema: "Emphysema",
      cancer: "Cancer",
      hypertension: "Hypertension",
      liverDisease: "Liver Disease",
      other: "Other",
    },
    abnormalEarSymptoms: "Ear Symptoms",
  },
};
