import { nationOptions } from "@/components/register/worker/Option";

export const TextWorkerPage = {
  th: {
    //RegisterWorkerPage
    headerWorker: "ลงทะเบียนผู้ประกอบอาชีพทำครกหิน จ.ลำปาง",
    personalInfo: "ข้อมูลส่วนบุคคล",
    workingInfo: "ข้อมูลการทำงาน",
    healthInfo: "ข้อมูลสุขภาพ",
    personalId: "เลขประจำตัวประชาชนหรือ Passport",
    gender: {
      title: "เพศ",
      male: "ชาย",
      female: "หญิง",
    },
    phone: "หมายเลขโทรศัพท์",
    dob: {
      title: "วันเดือนปีเกิด (พ.ศ.)",
      jan: "มกราคม",
      feb: "กุมภาพันธ์",
      mar: "มีนาคม",
      apr: "เมษายน",
      may: "พฤษภาคม",
      jun: "มิถุนายน",
      jul: "กรกฎาคม",
      aug: "สิงหาคม",
      sep: "กันยายน",
      oct: "ตุลาคม",
      nov: "พฤศจิกายน",
      dec: "ธันวาคม",
    },
    age: { title: "อายุ", unit: "ปี" },
    nation: "สัญชาติ",
    nationOptions: {
      "": "เลือกสัญชาติ",
      "ไทย": "ไทย",
      "ลาว": "ลาว",
      "เมียนมาร์": "เมียนมาร์",
      "กัมพูชา": "กัมพูชา",
      "อื่น ๆ": "อื่น ๆ",
    },
    address: "ที่อยู่ที่พักอาศัย",
    durationLiving: "ระยะเวลาที่อาศัยอยู่ในพื้นที่",
    bornAddress: "ที่อยู่ภูมิลำเนาเดิม (กรณีมีการย้ายถิ่นฐาน)",
    //WorkInfoTab
    vibrationValue: "ค่าการสั่นสะเทือน",
    x: "แกน X",
    y: "แกน Y",
    z: "แกน Z",
    accelerationAvg: "ค่าเฉลี่ยความเร่ง",
    exposeAvg: "ค่าเฉลี่ยรับสัมผัสใน 1 วัน",
    workHour: "ชั่วโมงการทำงานต่อวัน",
    workPerWeek: "วันทำงานต่อสัปดาห์",
    dayUnit: "วัน",
    workExperience: "ประสบการณ์ทำครกหิน",
    workAdress: "ที่อยู่หรือชื่อสถานที่ทำงาน",
    workplaceCharacter: "ลักษณะสถานที่ทำงาน",
    workOptions: {
        "" : "เลือกลักษณะสถานที่ทำงาน",
        "แยกจากที่พักอาศัย": "แยกจากที่พักอาศัย",
        "อยู่บริเวณที่พักอาศัย": "อยู่บริเวณที่พักอาศัย",
    },
    ppeTitle: "การใช้อุปกรณ์ป้องกันอันตรายส่วนบุคคล",
    ppeOptions: {no:"ไม่ได้ใช้",
        hatVeil: "หมวกผ้าคลุมหน้า",
        mask: "หน้ากากอนามัยแบบเยื่อกระดาษ 3 ชั้น",
        maskCotton: "หน้ากากอนามัยที่ผลิตจากผ้าฝ้าย",
        maskN95: "หน้ากากชนิด N95",
        earPlug: "ที่อุดหู",
        earMuff: "ที่ครอบหู",
        safetyGloves: "ถุงมือนิรภัย",
        safetyShoes: "รองเท้านิรภัย"
    }
    //HealthInfoTab
  },
  en: {
    //RegisterWorkerPage
    headerWorker: "Register Worker",
    personalInfo: "Personal Info",
    workingInfo: "Working Info",
    healthInfo: "Health Info",
    personalId: "ID Number or Passport",
    gender: {
      title: "Gender",
      male: "Male",
      female: "Female",
    },
    phone: "Phone Number",
    dob: {
      title: "Date of Birth",
      jan: "January",
      feb: "February",
      mar: "March",
      apr: "April",
      may: "May",
      jun: "June",
      jul: "July",
      aug: "August",
      sep: "September",
      oct: "October",
      nov: "November",
      dec: "December",
    },
    age: { title: "Age", unit: "years" },
    nation: "Nation",
    nationOptions: {
      "": "Select Nation",
      "ไทย": "Thai",
      "ลาว": "Lao",
      "เมียนมาร์": "Myanmar",
      "กัมพูชา": "Cambodia",
      "อื่น ๆ": "Other",
    },
    address: "Address",
    durationLiving: "Duration of Living",
    bornAddress: "Born Address",
    vibrationValue: "Vibration Value",
    x: "X-axis",
    y: "Y-axis",
    z: "Z-axis",
    accelerationAvg: "Acceleration Avg.",
    exposeAvg: "Expose Avg.",
    workHour: "Work Hour",
    workPerWeek: "Work Per Week",
    dayUnit: "Day",
    workExperience: "Work Experience",
    workAdress: "Workplace Address",
    workplaceCharacter: "Workplace Character",
    workOptions: {
        "" : "Select Workplace Character",
        "แยกจากที่พักอาศัย" : "Separate Home",
        "อยู่บริเวณที่พักอาศัย" : "Near Home",
    },
    ppeTitle: "Personal Protective Equipment Used",
    ppeOptions: {no:"Not Used",
        hatVeil: "Hat Veil",
        mask: "Mask",
        maskCotton: "Cotton Mask",
        maskN95: "N95 Mask",
        earPlug: "Ear Plug",
        earMuff: "Ear Muff",
        safetyGloves: "Safety Gloves",
        safetyShoes: "Safety Shoes"
    }
    //HealthInfoTab
  },
};
